services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: guestia-sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssw0rd!23
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver_data: